
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 01 21:39:14 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSEBRACEBRACKET = 4;
  public static final int PLUSPLUS = 24;
  public static final int CONST = 5;
  public static final int OPENSQUAREBRACKET = 9;
  public static final int CLOSESQUAREBRACKET = 10;
  public static final int NUMCONST = 47;
  public static final int SEMI = 7;
  public static final int CONTINUE = 17;
  public static final int MINUS = 37;
  public static final int LESS = 34;
  public static final int LOGICALOR = 26;
  public static final int MOREEQUAL = 33;
  public static final int LESSEQUAL = 35;
  public static final int COMMA = 8;
  public static final int CLASS = 11;
  public static final int EQUALEQUAL = 30;
  public static final int DIV = 39;
  public static final int PLUS = 36;
  public static final int IF = 21;
  public static final int THIS = 43;
  public static final int DOT = 29;
  public static final int LOGICALAND = 27;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 25;
  public static final int RETURN = 18;
  public static final int EQUAL = 6;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int CLOSEBRACKET = 13;
  public static final int MOD = 40;
  public static final int IDENT = 48;
  public static final int BREAK = 16;
  public static final int VOID = 14;
  public static final int EQUALMORE = 44;
  public static final int COLON = 46;
  public static final int FOREACH = 45;
  public static final int ELSE = 23;
  public static final int OPENBRACKET = 12;
  public static final int ENUM = 42;
  public static final int READ = 19;
  public static final int OPENBRACEBRACKET = 3;
  public static final int CHARCONST = 49;
  public static final int WHILE = 22;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int DO = 41;
  public static final int PRINT = 20;
  public static final int MORE = 32;
  public static final int UNEQUAL = 31;
}

